package modelo;
// Generated May 8, 2018 9:46:55 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Categoria generated by hbm2java
 */
public class Categoria implements java.io.Serializable {

    private int id;
    private String nombre;
    private Set preguntas = new HashSet(0);

    /**
     *
     */
    public Categoria() {
    }

    /**
     *
     * @param id
     * @param nombre
     */
    public Categoria(int id, String nombre) {
        this.id = id;
        this.nombre = nombre;
    }

    /**
     *
     * @param id
     * @param nombre
     * @param preguntas
     */
    public Categoria(int id, String nombre, Set preguntas) {
        this.id = id;
        this.nombre = nombre;
        this.preguntas = preguntas;
    }

    /**
     *
     * @param nombre
     */
    public Categoria(String nombre) {
        this.nombre = nombre;
    }

    /**
     *
     * @return
     */
    public int getId() {
        return this.id;
    }

    /**
     *
     * @param id
     */
    public void setId(int id) {
        this.id = id;
    }

    /**
     *
     * @return
     */
    public String getNombre() {
        return this.nombre;
    }

    /**
     *
     * @param nombre
     */
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    /**
     *
     * @return
     */
    public Set getPreguntas() {
        return this.preguntas;
    }

    /**
     *
     * @param preguntas
     */
    public void setPreguntas(Set preguntas) {
        this.preguntas = preguntas;
    }

}
