package modelo;
// Generated May 8, 2018 9:46:55 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Pregunta generated by hbm2java
 */
public class Pregunta  implements java.io.Serializable {


     private int id;
     private Categoria categoria;
     private Usuario usuario;
     private String titulo;
     private String contenido;
     private Date fecha;
     private Set respuestas = new HashSet(0);

    public Pregunta() {
    }

	
    public Pregunta(int id, Usuario usuario, String titulo, Date fecha) {
        this.id = id;
        this.usuario = usuario;
        this.titulo = titulo;
        this.fecha = fecha;
    }
    public Pregunta(int id, Categoria categoria, Usuario usuario, String titulo, String contenido, Date fecha, Set respuestas) {
       this.id = id;
       this.categoria = categoria;
       this.usuario = usuario;
       this.titulo = titulo;
       this.contenido = contenido;
       this.fecha = fecha;
       this.respuestas = respuestas;
    }
    public Pregunta(Categoria categoria, Usuario usuario, String titulo, String contenido, Date fecha) {       
       this.categoria = categoria;
       this.usuario = usuario;
       this.titulo = titulo;
       this.contenido = contenido;
       this.fecha = fecha;       
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public String getContenido() {
        return this.contenido;
    }
    
    public void setContenido(String contenido) {
        this.contenido = contenido;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Set getRespuestas() {
        return this.respuestas;
    }
    
    public void setRespuestas(Set respuestas) {
        this.respuestas = respuestas;
    }




}


