package modelo;
// Generated May 8, 2018 9:46:55 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Pregunta generated by hbm2java
 */
public class Pregunta implements java.io.Serializable {

    private int id;
    private Categoria categoria;
    private Usuario usuario;
    private String titulo;
    private String contenido;
    private Date fecha;
    private Set respuestas = new HashSet(0);

    /**
     *
     */
    public Pregunta() {
    }

    /**
     *
     * @param id
     * @param usuario
     * @param titulo
     * @param fecha
     */
    public Pregunta(int id, Usuario usuario, String titulo, Date fecha) {
        this.id = id;
        this.usuario = usuario;
        this.titulo = titulo;
        this.fecha = fecha;
    }

    /**
     *
     * @param id
     * @param categoria
     * @param usuario
     * @param titulo
     * @param contenido
     * @param fecha
     * @param respuestas
     */
    public Pregunta(int id, Categoria categoria, Usuario usuario, String titulo, String contenido, Date fecha, Set respuestas) {
        this.id = id;
        this.categoria = categoria;
        this.usuario = usuario;
        this.titulo = titulo;
        this.contenido = contenido;
        this.fecha = fecha;
        this.respuestas = respuestas;
    }

    /**
     *
     * @param categoria
     * @param usuario
     * @param titulo
     * @param contenido
     * @param fecha
     */
    public Pregunta(Categoria categoria, Usuario usuario, String titulo, String contenido, Date fecha) {
        this.categoria = categoria;
        this.usuario = usuario;
        this.titulo = titulo;
        this.contenido = contenido;
        this.fecha = fecha;
    }

    /**
     *
     * @return
     */
    public int getId() {
        return this.id;
    }

    /**
     *
     * @param id
     */
    public void setId(int id) {
        this.id = id;
    }

    /**
     *
     * @return
     */
    public Categoria getCategoria() {
        return this.categoria;
    }

    /**
     *
     * @param categoria
     */
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }

    /**
     *
     * @return
     */
    public Usuario getUsuario() {
        return this.usuario;
    }

    /**
     *
     * @param usuario
     */
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    /**
     *
     * @return
     */
    public String getTitulo() {
        return this.titulo;
    }

    /**
     *
     * @param titulo
     */
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }

    /**
     *
     * @return
     */
    public String getContenido() {
        return this.contenido;
    }

    /**
     *
     * @param contenido
     */
    public void setContenido(String contenido) {
        this.contenido = contenido;
    }

    /**
     *
     * @return
     */
    public Date getFecha() {
        return this.fecha;
    }

    /**
     *
     * @param fecha
     */
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    /**
     *
     * @return
     */
    public Set getRespuestas() {
        return this.respuestas;
    }

    /**
     *
     * @param respuestas
     */
    public void setRespuestas(Set respuestas) {
        this.respuestas = respuestas;
    }

}
