package modelo;
// Generated May 8, 2018 9:46:55 PM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Respuesta generated by hbm2java
 */
public class Respuesta implements java.io.Serializable {

    private int id;
    private Pregunta pregunta;
    private Usuario usuario;
    private String contenido;
    private Date fecha;

    /**
     *
     */
    public Respuesta() {
    }

    /**
     *
     * @param id
     * @param pregunta
     * @param usuario
     * @param contenido
     * @param fecha
     */
    public Respuesta(int id, Pregunta pregunta, Usuario usuario, String contenido, Date fecha) {
        this.id = id;
        this.pregunta = pregunta;
        this.usuario = usuario;
        this.contenido = contenido;
        this.fecha = fecha;
    }

    /**
     *
     * @return
     */
    public int getId() {
        return this.id;
    }

    /**
     *
     * @param id
     */
    public void setId(int id) {
        this.id = id;
    }

    /**
     *
     * @return
     */
    public Pregunta getPregunta() {
        return this.pregunta;
    }

    /**
     *
     * @param pregunta
     */
    public void setPregunta(Pregunta pregunta) {
        this.pregunta = pregunta;
    }

    /**
     *
     * @return
     */
    public Usuario getUsuario() {
        return this.usuario;
    }

    /**
     *
     * @param usuario
     */
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    /**
     *
     * @return
     */
    public String getContenido() {
        return this.contenido;
    }

    /**
     *
     * @param contenido
     */
    public void setContenido(String contenido) {
        this.contenido = contenido;
    }

    /**
     *
     * @return
     */
    public Date getFecha() {
        return this.fecha;
    }

    /**
     *
     * @param fecha
     */
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

}
