package modelo;
// Generated Apr 10, 2018 7:46:24 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Respuesta generated by hbm2java
 */
public class Respuesta  implements java.io.Serializable {


     private int id;
     private Pregunta pregunta;
     private Usuario usuario;
     private String contenido;
     private Date fecha;

    public Respuesta() {
    }

    public Respuesta(int id, Pregunta pregunta, Usuario usuario, String contenido, Date fecha) {
       this.id = id;
       this.pregunta = pregunta;
       this.usuario = usuario;
       this.contenido = contenido;
       this.fecha = fecha;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Pregunta getPregunta() {
        return this.pregunta;
    }
    
    public void setPregunta(Pregunta pregunta) {
        this.pregunta = pregunta;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getContenido() {
        return this.contenido;
    }
    
    public void setContenido(String contenido) {
        this.contenido = contenido;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }




}


