package modelo;
// Generated May 8, 2018 9:46:55 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario implements java.io.Serializable {

    private int id;
    private Carrera carrera;
    private String nombre;
    private String email;
    private String password;
    private Date fechaRegistro;
    private boolean esAdmin;
    private byte[] foto;
    private Set preguntas = new HashSet(0);
    private Set respuestas = new HashSet(0);

    /**
     *
     */
    public Usuario() {
    }

    /**
     *
     * @param id
     * @param nombre
     * @param email
     * @param password
     * @param fechaRegistro
     * @param esAdmin
     */
    public Usuario(int id, String nombre, String email, String password, Date fechaRegistro, boolean esAdmin) {
        this.id = id;
        this.nombre = nombre;
        this.email = email;
        this.password = password;
        this.fechaRegistro = fechaRegistro;
        this.esAdmin = esAdmin;
    }

    /**
     *
     * @param id
     * @param carrera
     * @param nombre
     * @param email
     * @param password
     * @param fechaRegistro
     * @param esAdmin
     * @param foto
     * @param preguntas
     * @param respuestas
     */
    public Usuario(int id, Carrera carrera, String nombre, String email, String password, Date fechaRegistro, boolean esAdmin, byte[] foto, Set preguntas, Set respuestas) {
        this.id = id;
        this.carrera = carrera;
        this.nombre = nombre;
        this.email = email;
        this.password = password;
        this.fechaRegistro = fechaRegistro;
        this.esAdmin = esAdmin;
        this.foto = foto;
        this.preguntas = preguntas;
        this.respuestas = respuestas;
    }

    /**
     *
     * @param nombre
     * @param email
     * @param password
     * @param fechaRegistro
     * @param esAdmin
     */
    public Usuario(String nombre, String email, String password, Date fechaRegistro,
            boolean esAdmin) {
        this.nombre = nombre;
        this.email = email;
        this.password = password;
        this.fechaRegistro = fechaRegistro;
        this.esAdmin = esAdmin;
    }

    /**
     *
     * @return
     */
    public int getId() {
        return this.id;
    }

    /**
     *
     * @param id
     */
    public void setId(int id) {
        this.id = id;
    }

    /**
     *
     * @return
     */
    public Carrera getCarrera() {
        return this.carrera;
    }

    /**
     *
     * @param carrera
     */
    public void setCarrera(Carrera carrera) {
        this.carrera = carrera;
    }

    /**
     *
     * @return
     */
    public String getNombre() {
        return this.nombre;
    }

    /**
     *
     * @param nombre
     */
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    /**
     *
     * @return
     */
    public String getEmail() {
        return this.email;
    }

    /**
     *
     * @param email
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     *
     * @return
     */
    public String getPassword() {
        return this.password;
    }

    /**
     *
     * @param password
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     *
     * @return
     */
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }

    /**
     *
     * @param fechaRegistro
     */
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }

    /**
     *
     * @return
     */
    public boolean isEsAdmin() {
        return this.esAdmin;
    }

    /**
     *
     * @param esAdmin
     */
    public void setEsAdmin(boolean esAdmin) {
        this.esAdmin = esAdmin;
    }

    /**
     *
     * @return
     */
    public byte[] getFoto() {
        return this.foto;
    }

    /**
     *
     * @param foto
     */
    public void setFoto(byte[] foto) {
        this.foto = foto;
    }

    /**
     *
     * @return
     */
    public Set getPreguntas() {
        return this.preguntas;
    }

    /**
     *
     * @param preguntas
     */
    public void setPreguntas(Set preguntas) {
        this.preguntas = preguntas;
    }

    /**
     *
     * @return
     */
    public Set getRespuestas() {
        return this.respuestas;
    }

    /**
     *
     * @param respuestas
     */
    public void setRespuestas(Set respuestas) {
        this.respuestas = respuestas;
    }

}
