package modelo;
// Generated May 8, 2018 9:46:55 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int id;
     private Carrera carrera;
     private String nombre;
     private String email;
     private String password;
     private Date fechaRegistro;
     private boolean esAdmin;
     private byte[] foto;
     private Set preguntas = new HashSet(0);
     private Set respuestas = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(int id, String nombre, String email, String password, Date fechaRegistro, boolean esAdmin) {
        this.id = id;
        this.nombre = nombre;
        this.email = email;
        this.password = password;
        this.fechaRegistro = fechaRegistro;
        this.esAdmin = esAdmin;
    }
    public Usuario(int id, Carrera carrera, String nombre, String email, String password, Date fechaRegistro, boolean esAdmin, byte[] foto, Set preguntas, Set respuestas) {
       this.id = id;
       this.carrera = carrera;
       this.nombre = nombre;
       this.email = email;
       this.password = password;
       this.fechaRegistro = fechaRegistro;
       this.esAdmin = esAdmin;
       this.foto = foto;
       this.preguntas = preguntas;
       this.respuestas = respuestas;
    }
    public Usuario(String nombre, String email, String password, Date fechaRegistro,
            boolean esAdmin) {
        this.nombre = nombre;
        this.email = email;
        this.password = password;
        this.fechaRegistro = fechaRegistro;
        this.esAdmin = esAdmin;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Carrera getCarrera() {
        return this.carrera;
    }
    
    public void setCarrera(Carrera carrera) {
        this.carrera = carrera;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public boolean isEsAdmin() {
        return this.esAdmin;
    }
    
    public void setEsAdmin(boolean esAdmin) {
        this.esAdmin = esAdmin;
    }
    public byte[] getFoto() {
        return this.foto;
    }
    
    public void setFoto(byte[] foto) {
        this.foto = foto;
    }
    public Set getPreguntas() {
        return this.preguntas;
    }
    
    public void setPreguntas(Set preguntas) {
        this.preguntas = preguntas;
    }
    public Set getRespuestas() {
        return this.respuestas;
    }
    
    public void setRespuestas(Set respuestas) {
        this.respuestas = respuestas;
    }

}


