package modelo;
// Generated May 8, 2018 9:46:55 PM by Hibernate Tools 4.3.1

/**
 * UsuarioSinValidar generated by hbm2java
 */
public class UsuarioSinValidar implements java.io.Serializable {

    private int id;
    private String nombre;
    private String email;
    private String password;

    /**
     *
     */
    public UsuarioSinValidar() {
    }

    /**
     *
     * @param id
     * @param nombre
     * @param email
     * @param password
     */
    public UsuarioSinValidar(int id, String nombre, String email, String password) {
        this.id = id;
        this.nombre = nombre;
        this.email = email;
        this.password = password;
    }

    /**
     *
     * @param nombre
     * @param email
     * @param password
     */
    public UsuarioSinValidar(String nombre, String email, String password) {
        this.nombre = nombre;
        this.email = email;
        this.password = password;
    }

    /**
     *
     * @return
     */
    public int getId() {
        return this.id;
    }

    /**
     *
     * @param id
     */
    public void setId(int id) {
        this.id = id;
    }

    /**
     *
     * @return
     */
    public String getNombre() {
        return this.nombre;
    }

    /**
     *
     * @param nombre
     */
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    /**
     *
     * @return
     */
    public String getEmail() {
        return this.email;
    }

    /**
     *
     * @param email
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     *
     * @return
     */
    public String getPassword() {
        return this.password;
    }

    /**
     *
     * @param password
     */
    public void setPassword(String password) {
        this.password = password;
    }

}
