package modelo;
// Generated Apr 10, 2018 7:46:24 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int id;
     private Carrera carrera;
     private String nombre;
     private String email;
     private String password;
     private Date fechaRegistro;
     private Set preguntas = new HashSet(0);
     private Administrador administrador;
     private Set respuestas = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(int id, String nombre, String email, String password, Date fechaRegistro) {
        this.id = id;
        this.nombre = nombre;
        this.email = email;
        this.password = password;
        this.fechaRegistro = fechaRegistro;
    }
    public Usuario(int id, Carrera carrera, String nombre, String email, String password, Date fechaRegistro, Set preguntas, Administrador administrador, Set respuestas) {
       this.id = id;
       this.carrera = carrera;
       this.nombre = nombre;
       this.email = email;
       this.password = password;
       this.fechaRegistro = fechaRegistro;
       this.preguntas = preguntas;
       this.administrador = administrador;
       this.respuestas = respuestas;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Carrera getCarrera() {
        return this.carrera;
    }
    
    public void setCarrera(Carrera carrera) {
        this.carrera = carrera;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public Set getPreguntas() {
        return this.preguntas;
    }
    
    public void setPreguntas(Set preguntas) {
        this.preguntas = preguntas;
    }
    public Administrador getAdministrador() {
        return this.administrador;
    }
    
    public void setAdministrador(Administrador administrador) {
        this.administrador = administrador;
    }
    public Set getRespuestas() {
        return this.respuestas;
    }
    
    public void setRespuestas(Set respuestas) {
        this.respuestas = respuestas;
    }




}


