package modelo;
// Generated Apr 3, 2018 11:51:40 PM by Hibernate Tools 4.3.1



/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int id;
     private String nombre;
     private String email;
     private String password;

    public Usuario() {
    }

	
    public Usuario(int id, String nombre, String password) {
        this.id = id;
        this.nombre = nombre;
        this.password = password;
    }
    public Usuario(int id, String nombre, String email, String password) {
       this.id = id;
       this.nombre = nombre;
       this.email = email;
       this.password = password;
    }
    
    public Usuario(String nombre, String email, String password) {
       this.nombre = nombre;
       this.email = email;
       this.password = password;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


