package Modelo;
// Generated Apr 14, 2018 10:24:11 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int id;
     private String nombre;
     private String email;
     private String password;
     private Date fechaRegistro;
     private Date fechaNacimiento;
     private Set preguntas = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(int id) {
        this.id = id;
    }
    
    public Usuario(String nombre, String email, String password, Date fechaRegistro, Date fechaNacimiento, Set preguntas) {     
       this.nombre = nombre;
       this.email = email;
       this.password = password;
       this.fechaRegistro = fechaRegistro;
       this.fechaNacimiento = fechaNacimiento;
       this.preguntas = preguntas;
    }
    
    public Usuario(int id, String nombre, String email, String password, Date fechaRegistro, Date fechaNacimiento, Set preguntas) {
       this.id = id;
       this.nombre = nombre;
       this.email = email;
       this.password = password;
       this.fechaRegistro = fechaRegistro;
       this.fechaNacimiento = fechaNacimiento;
       this.preguntas = preguntas;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }
    public Set getPreguntas() {
        return this.preguntas;
    }
    
    public void setPreguntas(Set preguntas) {
        this.preguntas = preguntas;
    }
}


